# Generated by Django 4.1 on 2022-08-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='xategorias',
            new_name='categorias',
        ),
    ]
